import axios from "axios";import { getAccessToken } from "./supabaseAuth";
const videoApi=axios.create({baseURL:import.meta.env.VITE_VIDEO_API_BASE||"http://127.0.0.1:8765/api",timeout:15000});const documentBase=import.meta.env.VITE_DOCUMENT_API_BASE||"http://127.0.0.1:8000";videoApi.interceptors.request.use(async config=>{const token=await getAccessToken();if(!token)throw new Error("Sign in to use this feature.");config.headers.Authorization=`Bearer ${token}`;return config;});async function authHeaders(extra:HeadersInit={}){const token=await getAccessToken();if(!token)throw new Error("Sign in to use this feature.");return{Authorization:`Bearer ${token}`,...extra};}
async function blobError(error:unknown,fallback:string):Promise<never>{if(axios.isAxiosError(error)){const responseData=error.response?.data;if(responseData instanceof Blob){try{const data=JSON.parse(await responseData.text())as{detail?:string};if(data.detail)throw new Error(data.detail);}catch(reason){if(reason instanceof Error&&reason.message!=="Unexpected end of JSON input")throw reason;}}throw new Error(error.response?`${fallback} (HTTP ${error.response.status})`:"Could not connect to the video backend. Check the backend and Cloudflare Tunnel.");}throw error instanceof Error?error:new Error(fallback);}
type VideoDownloadJob={job_id:string;status:"queued"|"running"|"completed"|"failed";filename?:string;error?:string};
const wait=(milliseconds:number)=>new Promise(resolve=>setTimeout(resolve,milliseconds));
export async function downloadVideo(url:string,quality:string,browser:string){const body=new FormData();body.append("url",url);body.append("quality",quality);body.append("cookie_browser",browser);try{const created=(await videoApi.post<VideoDownloadJob>("/downloads/jobs",body)).data;const deadline=Date.now()+2*60*60*1000;let job=created;while(job.status!=="completed"){if(job.status==="failed")throw new Error(job.error||"Could not download the video.");if(Date.now()>=deadline)throw new Error("The video download timed out.");await wait(2000);job=(await videoApi.get<VideoDownloadJob>(`/downloads/jobs/${created.job_id}/status`)).data;}return(await videoApi.get<Blob>(`/downloads/jobs/${created.job_id}/result`,{responseType:"blob",timeout:0})).data;}catch(error){return await blobError(error,"Could not download the video.");}}
export async function compressVideo(file:File,preset:string,format:string){if(file.size>80*1024*1024)return compressVideoInChunks(file,preset,format);const body=new FormData();body.append("file",file);body.append("preset",preset);body.append("output_format",format);try{return(await videoApi.post<Blob>("/compression/process",body,{responseType:"blob",timeout:0})).data;}catch(error){return await blobError(error,"Could not compress the video.");}}
async function compressVideoInChunks(file:File,preset:string,format:string){try{const started=await videoApi.post<{upload_id:string}>("/compression/uploads",{filename:file.name,size:file.size});const uploadId=started.data.upload_id;const chunkSize=8*1024*1024;for(let offset=0,index=0;offset<file.size;offset+=chunkSize,index+=1){const body=new FormData();body.append("index",String(index));body.append("chunk",file.slice(offset,offset+chunkSize),`${file.name}.part-${index}`);await videoApi.post(`/compression/uploads/${uploadId}/chunks`,body,{timeout:0});}return(await videoApi.post<Blob>(`/compression/uploads/${uploadId}/process`,{preset,format},{responseType:"blob",timeout:0})).data;}catch(error){return await blobError(error,"Could not upload or compress the video.");}}
async function audioOperation(path:string,file:File){const body=new FormData();body.append("file",file);try{return(await videoApi.post<Blob>(path,body,{responseType:"blob",timeout:0})).data;}catch(error){return await blobError(error,"Could not process the audio.");}}export const extractAudio=(file:File)=>audioOperation("/audio/extract",file);export const muteVideo=(file:File)=>audioOperation("/audio/mute",file);
export async function renderVideoProject(clips:File[],trims:Array<{start:number;end:number}>,texts:Array<{text:string;start:number;end:number}>,music:File|null){const body=new FormData();clips.forEach(clip=>body.append("clips",clip));body.append("trims",JSON.stringify(trims));body.append("texts",JSON.stringify(texts));body.append("cut_mode","accurate");if(music)body.append("music",music);try{return(await videoApi.post<Blob>("/editor/render",body,{responseType:"blob",timeout:0})).data;}catch(error){return await blobError(error,"Could not export the video project.");}}
async function json<T>(response:Response):Promise<T>{const data=await response.json().catch(()=>({}))as{detail?:string};if(!response.ok)throw new Error(data.detail||"An error occurred.");return data as T;}export type DocumentJob={job_id:string;status?:string;output_file?:string;download_url?:string;[key:string]:unknown};
export async function convertDocument(file:File,settings:Record<string,unknown>){let sourceFile=file;const selectedPages=String(settings.pages||"").trim();if(selectedPages){const isPdf=file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf");if(!isPdf)throw new Error("Page selection is available only for PDF files.");const selected=await splitPdf(file,selectedPages,"merged",`${file.name.replace(/\.pdf$/i,"")}-selected.pdf`);sourceFile=new File([selected.blob],selected.filename,{type:"application/pdf"});}const call=async(path:string,init:RequestInit,step:string)=>{try{return await fetch(`${documentBase}${path}`,init);}catch{throw new Error(`Lost connection to the document backend while ${step}. Check the backend and Cloudflare Tunnel.`);}};const job=await json<DocumentJob>(await call("/api/jobs",{method:"POST",headers:await authHeaders({"Content-Type":"application/json"}),body:JSON.stringify(settings)},"creating the job"));const upload=new FormData();upload.append("job_id",job.job_id);upload.append("file",sourceFile);await json(await call("/api/upload",{method:"POST",headers:await authHeaders(),body:upload},"uploading the file"));return json<DocumentJob>(await call("/api/convert",{method:"POST",headers:await authHeaders({"Content-Type":"application/json"}),body:JSON.stringify({job_id:job.job_id})},"converting the document"));}
export function saveBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const anchor=document.createElement("a");anchor.href=url;anchor.download=filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}export function documentDownloadUrl(job:DocumentJob){if(job.download_url)return job.download_url.startsWith("http")?job.download_url:`${documentBase}${job.download_url}`;return`${documentBase}/api/jobs/${job.job_id}/download`;}
export async function downloadDocument(job:DocumentJob){const response=await fetch(documentDownloadUrl(job),{headers:await authHeaders()});if(!response.ok)return responseError(response,"Could not download the document.");return{blob:await response.blob(),filename:responseFilename(response,`loca-document.${String(job.output_file||"docx").split(".").pop()||"docx"}`)};}export type PdfInfo={filename:string;size:number;pages:number};export type DownloadResult={blob:Blob;filename:string};
async function responseError(response:Response,fallback:string):Promise<never>{try{const data=await response.json()as{detail?:string};throw new Error(data.detail||fallback);}catch(error){if(error instanceof Error&&error.message!=="Unexpected end of JSON input")throw error;}throw new Error(fallback);}function responseFilename(response:Response,fallback:string){const disposition=response.headers.get("Content-Disposition")||"";const utf=disposition.match(/filename\*=UTF-8''([^;]+)/i);if(utf){try{return decodeURIComponent(utf[1]);}catch{return utf[1];}}return disposition.match(/filename="?([^";]+)"?/i)?.[1]||fallback;}
export async function inspectPdf(file:File):Promise<PdfInfo>{const body=new FormData();body.append("file",file);const response=await fetch(`${documentBase}/api/pdf/info`,{method:"POST",headers:await authHeaders(),body});if(!response.ok)return responseError(response,"Could not read PDF information.");return response.json()as Promise<PdfInfo>;}
export async function splitPdf(file:File,pageRanges:string,outputMode:"merged"|"separate",outputName:string):Promise<DownloadResult>{const body=new FormData();body.append("file",file);body.append("page_ranges",pageRanges);body.append("output_mode",outputMode);body.append("output_name",outputName);const response=await fetch(`${documentBase}/api/pdf/split`,{method:"POST",headers:await authHeaders(),body});if(!response.ok)return responseError(response,"Could not split the PDF.");const fallback=outputMode==="separate"&&pageRanges.includes("|")?`${outputName||"document_cut"}.zip`:`${outputName||"document_cut"}.pdf`;return{blob:await response.blob(),filename:responseFilename(response,fallback)};}
export async function mergePdfs(files:File[],outputName:string):Promise<DownloadResult>{const body=new FormData();files.forEach(file=>body.append("files[]",file));body.append("output_name",outputName);const response=await fetch(`${documentBase}/api/pdf/merge`,{method:"POST",headers:await authHeaders(),body});if(!response.ok)return responseError(response,"Could not merge the PDFs.");return{blob:await response.blob(),filename:responseFilename(response,`${outputName||"merged-document"}.pdf`) };}
export async function rotateVideo(file:File,rotation:number,mirror:boolean){const body=new FormData();body.append("file",file);body.append("rotation",String(rotation));body.append("mirror",String(mirror));try{return(await videoApi.post<Blob>("/video/rotate",body,{responseType:"blob",timeout:0})).data;}catch(error){return await blobError(error,"Could not rotate the video.");}}
export async function rotatePdf(file:File,rotation:number,pageRanges:string,outputName:string):Promise<DownloadResult>{const body=new FormData();body.append("file",file);body.append("rotation",String(rotation));body.append("page_ranges",pageRanges);body.append("output_name",outputName);const response=await fetch(`${documentBase}/api/pdf/rotate`,{method:"POST",headers:await authHeaders(),body});if(!response.ok)return responseError(response,"Could not rotate the PDF.");return{blob:await response.blob(),filename:responseFilename(response,`${outputName||"document_rotated"}.pdf`)};}
