import { useEffect, useMemo, useState } from "react";
import { LockKeyhole, Plus, RefreshCw, ShieldCheck, Trash2, UserCog } from "lucide-react";
import { createUser, deleteUser, listAudit, listUsers, updateUser, type AdminUser, type AuditEntry } from "../services/adminApi";

export default function AdminPage() {
  const [users, setUsers] = useState<AdminUser[]>([]); const [audit, setAudit] = useState<AuditEntry[]>([]); const [tab, setTab] = useState<"users" | "audit">("users"); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ email: "", password: "", role: "user", status: "active", expires_at: "", force_password_change: true });
  const stats = useMemo(() => ({ total: users.length, active: users.filter(x => x.status === "active").length, locked: users.filter(x => x.status === "locked").length, admins: users.filter(x => x.role === "admin").length }), [users]);
  async function load() { setBusy(true); setError(""); try { const [nextUsers, nextAudit] = await Promise.all([listUsers(), listAudit()]); setUsers(nextUsers); setAudit(nextAudit); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tải dữ liệu quản trị."); } finally { setBusy(false); } }
  useEffect(() => { void load(); }, []);
  async function add(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { await createUser({ ...form, expires_at: form.expires_at ? new Date(form.expires_at).toISOString() : null }); setForm({ email: "", password: "", role: "user", status: "active", expires_at: "", force_password_change: true }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể tạo tài khoản."); } finally { setBusy(false); } }
  async function change(user: AdminUser, field: "role" | "status", value: string) { setBusy(true); try { await updateUser(user.user_id, { [field]: value }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể cập nhật tài khoản."); } finally { setBusy(false); } }
  async function remove(user: AdminUser) { if (!window.confirm(`Xóa tài khoản ${user.email}? Thao tác này không thể hoàn tác.`)) return; setBusy(true); try { await deleteUser(user.user_id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể xóa tài khoản."); } finally { setBusy(false); } }
  return <section className="admin-page"><div className="page-heading"><div><span className="eyebrow">QUẢN TRỊ HỆ THỐNG</span><h2>Quản lý tài khoản</h2><p>Phân quyền và kiểm soát quyền truy cập Loca Editor.</p></div><button className="secondary-action" onClick={() => void load()} disabled={busy}><RefreshCw className={busy ? "spin" : ""} /> Tải lại</button></div>{error && <div className="notice error">{error}</div>}
    <div className="admin-stats"><div><UserCog/><span><strong>{stats.total}</strong><small>Tổng tài khoản</small></span></div><div><ShieldCheck/><span><strong>{stats.active}</strong><small>Đang hoạt động</small></span></div><div><LockKeyhole/><span><strong>{stats.locked}</strong><small>Đã khóa</small></span></div><div><ShieldCheck/><span><strong>{stats.admins}</strong><small>Quản trị viên</small></span></div></div>
    <div className="admin-tabs"><button className={tab === "users" ? "active" : ""} onClick={() => setTab("users")}>Tài khoản</button><button className={tab === "audit" ? "active" : ""} onClick={() => setTab("audit")}>Nhật ký quản trị</button></div>
    {tab === "users" ? <div className="admin-grid"><form className="card admin-create" onSubmit={add}><div className="card-title compact"><span className="soft-icon"><Plus/></span><div><h3>Tạo tài khoản</h3><p>Mật khẩu tạm thời sẽ phải đổi sau lần đăng nhập đầu.</p></div></div><label className="field"><span>Email</span><input type="email" required value={form.email} onChange={e => setForm({...form,email:e.target.value})}/></label><label className="field"><span>Mật khẩu tạm</span><input type="password" minLength={8} required value={form.password} onChange={e => setForm({...form,password:e.target.value})}/></label><div className="form-grid"><label className="field"><span>Vai trò</span><select value={form.role} onChange={e => setForm({...form,role:e.target.value})}><option value="user">User</option><option value="agent">Agent</option><option value="admin">Admin</option></select></label><label className="field"><span>Trạng thái</span><select value={form.status} onChange={e => setForm({...form,status:e.target.value})}><option value="active">Active</option><option value="locked">Locked</option><option value="expired">Expired</option></select></label></div><label className="field"><span>Ngày hết hạn (không bắt buộc)</span><input type="datetime-local" value={form.expires_at} onChange={e => setForm({...form,expires_at:e.target.value})}/></label><label className="admin-check"><input type="checkbox" checked={form.force_password_change} onChange={e => setForm({...form,force_password_change:e.target.checked})}/> Bắt buộc đổi mật khẩu lần đầu</label><button className="primary" disabled={busy}><Plus/> Tạo tài khoản</button></form>
      <div className="card admin-list"><h3>Danh sách tài khoản</h3><div className="admin-table-wrap"><table><thead><tr><th>Email</th><th>Vai trò</th><th>Trạng thái</th><th>Hết hạn</th><th></th></tr></thead><tbody>{users.map(user => <tr key={user.user_id}><td><strong>{user.email}</strong><small>{user.force_password_change ? "Phải đổi mật khẩu" : "Đã xác nhận mật khẩu"}</small></td><td><select value={user.role} disabled={busy} onChange={e => void change(user,"role",e.target.value)}><option value="admin">Admin</option><option value="agent">Agent</option><option value="user">User</option></select></td><td><select value={user.status} disabled={busy} onChange={e => void change(user,"status",e.target.value)}><option value="active">Active</option><option value="locked">Locked</option><option value="expired">Expired</option></select></td><td>{user.expires_at ? new Date(user.expires_at).toLocaleString("vi-VN") : "Không giới hạn"}</td><td><button className="danger-icon" onClick={() => void remove(user)} aria-label={`Xóa ${user.email}`}><Trash2/></button></td></tr>)}</tbody></table></div></div></div> : <div className="card audit-list"><table><thead><tr><th>Thời gian</th><th>Hành động</th><th>Người thực hiện</th><th>Tài khoản đích</th></tr></thead><tbody>{audit.map(entry => <tr key={entry.id}><td>{new Date(entry.created_at).toLocaleString("vi-VN")}</td><td><strong>{entry.action}</strong></td><td>{entry.admin_user_id || "Hệ thống"}</td><td>{entry.target_user_id || "—"}</td></tr>)}</tbody></table></div>}
  </section>;
}
