import { useEffect, useMemo, useState } from "react";
import { Gauge, Save, Sparkles } from "lucide-react";
import FileDrop from "../components/FileDrop";
import TimedActionButton from "../components/TimedActionButton";
import { useElapsedTimer } from "../hooks/useElapsedTimer";
import { compressVideo, saveBlob } from "../services/api";
export default function CompressPage() {
  const [file,setFile]=useState<File|null>(null); const [preset,setPreset]=useState("balanced"); const [format,setFormat]=useState("mp4"); const [busy,setBusy]=useState(false); const [result,setResult]=useState<Blob|null>(null); const [error,setError]=useState(""); const timer=useElapsedTimer(); const preview=useMemo(()=>file?URL.createObjectURL(file):"",[file]); useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  async function start(){if(!file||busy)return;timer.start();try{setBusy(true);setError("");setResult(null);setResult(await compressVideo(file,preset,format));}catch(e){setError(e instanceof Error?e.message:"Could not compress the video.");}finally{setBusy(false);timer.stop();}}
  return <section><div className="page-heading"><div><span className="eyebrow">VIDEO OPTIMIZATION</span><h2>Compress Video</h2><p>Reduce file size while keeping control of output quality.</p></div></div>{error&&<div className="notice error">{error}</div>}<div className="split equal compress-layout"><article className="card"><div className="card-title"><span className="number">01</span><div><h3>Select video</h3><p>Choose a source file and compression level.</p></div></div><FileDrop file={file} accept="video/*" hint="MP4, MOV, MKV, WebM, or AVI" onChange={v=>{setFile(v);setResult(null);timer.reset();}}/><h4 className="section-label">COMPRESSION LEVEL</h4><div className="preset-list">{[["light","Light","Fast · high quality","~25%"],["balanced","Balanced","Ideal for sharing","~50%"],["max","Maximum","Smallest file size","~70%"]].map(item=><button key={item[0]} className={preset===item[0]?"preset active":"preset"} onClick={()=>setPreset(item[0])}><i/><span><strong>{item[1]}</strong><small>{item[2]}</small></span><b>{item[3]}</b></button>)}</div></article><article className="right-stack"><div className="card preview-card"><div className="card-title compact"><span className="soft-icon"><Gauge/></span><div><h3>Video preview</h3><p>Review the file before compression.</p></div></div><div className="video-frame">{preview?<video src={preview} controls/>:<span>No video selected</span>}</div></div><div className="card output-card"><h3>Output settings</h3><label className="field"><span>Format</span><select value={format} onChange={e=>{setFormat(e.target.value);setResult(null);timer.reset();}}><option value="mp4">MP4 · Most compatible</option><option value="mov">MOV · Apple</option><option value="mkv">MKV · High quality</option><option value="webm">WebM · For the web</option></select></label><div className="estimate"><Sparkles/><span><strong>{result?"Compression complete":"Estimated file size"}</strong><small>{result?`${(result.size/1048576).toFixed(1)} MB · ready to save`:file?"Final size depends on the video content":"Select a video to begin"}</small></span></div><TimedActionButton label="Start compression" loadingLabel="Compressing..." isRunning={timer.isRunning} elapsedTime={timer.formattedTime} disabled={!file||busy} onClick={start} success={!!result} error={!!error}/>{result&&<button className="primary result-download" onClick={()=>saveBlob(result,`loca-compressed.${format}`)}><Save/> Save video</button>}</div></article></div></section>;
}
