import { useEffect, useMemo, useState } from "react";
import { Gauge, Save, Sparkles } from "lucide-react";
import FileDrop from "../components/FileDrop";
import { compressVideo, saveBlob } from "../services/api";

export default function CompressPage() {
  const [file, setFile] = useState<File | null>(null); const [preset, setPreset] = useState("balanced"); const [format, setFormat] = useState("mp4"); const [busy, setBusy] = useState(false); const [result, setResult] = useState<Blob | null>(null); const [error, setError] = useState("");
  const preview = useMemo(() => file ? URL.createObjectURL(file) : "", [file]); useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); }, [preview]);
  async function start() { if (!file) return; try { setBusy(true); setError(""); setResult(null); setResult(await compressVideo(file, preset, format)); } catch (e) { setError(e instanceof Error ? e.message : "Không thể nén video."); } finally { setBusy(false); } }
  return <section><div className="page-heading"><div><span className="eyebrow">TỐI ƯU VIDEO</span><h2>Nén video</h2><p>Giảm dung lượng trong khi vẫn kiểm soát chất lượng đầu ra.</p></div></div>{error && <div className="notice error">{error}</div>}
    <div className="split equal compress-layout"><article className="card"><div className="card-title"><span className="number">01</span><div><h3>Chọn video</h3><p>Chọn tệp nguồn và mức nén mong muốn.</p></div></div><FileDrop file={file} accept="video/*" hint="MP4, MOV, MKV, WebM hoặc AVI" onChange={value => { setFile(value); setResult(null); }} />
      <h4 className="section-label">MỨC NÉN</h4><div className="preset-list">{[["light","Nén nhẹ","Nhanh · chất lượng cao","~25%"],["balanced","Cân bằng","Phù hợp để chia sẻ","~50%"],["max","Nén tối đa","Ưu tiên tệp nhỏ nhất","~70%"]].map(item => <button key={item[0]} className={preset === item[0] ? "preset active" : "preset"} onClick={() => setPreset(item[0])}><i/><span><strong>{item[1]}</strong><small>{item[2]}</small></span><b>{item[3]}</b></button>)}</div>
    </article><article className="right-stack"><div className="card preview-card"><div className="card-title compact"><span className="soft-icon"><Gauge /></span><div><h3>Xem trước video</h3><p>Kiểm tra tệp trước khi nén.</p></div></div><div className="video-frame">{preview ? <video src={preview} controls /> : <span>Chưa có video để xem trước</span>}</div></div>
      <div className="card output-card"><h3>Thiết lập đầu ra</h3><label className="field"><span>Định dạng</span><select value={format} onChange={e => { setFormat(e.target.value); setResult(null); }}><option value="mp4">MP4 · Phổ biến nhất</option><option value="mov">MOV · Apple</option><option value="mkv">MKV · Chất lượng cao</option><option value="webm">WebM · Dành cho web</option></select></label><div className="estimate"><Sparkles /><span><strong>{result ? "Nén hoàn tất" : "Ước tính dung lượng"}</strong><small>{result ? `${(result.size / 1048576).toFixed(1)} MB · sẵn sàng lưu` : file ? "Dung lượng sẽ phụ thuộc nội dung video" : "Chọn video để bắt đầu"}</small></span></div>{result ? <button className="primary wide" onClick={() => saveBlob(result, `loca-compressed.${format}`)}><Save /> Lưu video</button> : <button className="primary wide" disabled={!file || busy} onClick={start}>{busy ? "Đang nén..." : "Bắt đầu nén"}</button>}</div>
    </article></div></section>;
}
