import { useState } from "react";
import { Download, LoaderCircle } from "lucide-react";
import FileDrop from "../components/FileDrop";
import PdfPreview from "../components/PdfPreview";
import TimedActionButton from "../components/TimedActionButton";
import { useElapsedTimer } from "../hooks/useElapsedTimer";
import { convertDocument, downloadDocument, saveBlob, type DocumentJob } from "../services/api";

export default function DocumentPage() {
  const [file, setFile] = useState<File | null>(null); const [format, setFormat] = useState("docx"); const [mode, setMode] = useState("hybrid"); const [pages, setPages] = useState(""); const [language, setLanguage] = useState("auto"); const [busy, setBusy] = useState(false); const [job, setJob] = useState<DocumentJob | null>(null); const [error, setError] = useState(""); const timer = useElapsedTimer();
  const isPdf=Boolean(file&&(file.type==="application/pdf"||file.name.toLowerCase().endsWith(".pdf")));
  function chooseFile(value:File|null){setJob(null);setError("");timer.reset();if(!value){setFile(null);setPages("");return;}if(!/\.(pdf|png|jpe?g|tiff?|bmp)$/i.test(value.name)){setFile(null);setPages("");setError("Only PDF, PNG, JPG, TIFF, and BMP files are accepted.");return;}setFile(value);if(!value.name.toLowerCase().endsWith(".pdf"))setPages("");}
  async function start() { if (!file || busy) return; timer.start(); try { setBusy(true); setError(""); setJob(null); setJob(await convertDocument(file, { output_format: format, mode, pages:isPdf?pages:"", ocr_language: language })); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not convert the document."); } finally { setBusy(false); timer.stop(); } }
  return <section><div className="page-heading"><div><span className="eyebrow">DOCUMENT EDITOR</span><h2>Convert Document</h2><p>Select a file, configure the output, and preview it on the same screen.</p></div></div>
    <div className="document-layout"><article className="card document-controls"><div className="card-title"><span className="number">01</span><div><h3>Input file and options</h3><p>Configure the conversion process.</p></div></div><FileDrop file={file} accept=".pdf,.png,.jpg,.jpeg,.tif,.tiff,.bmp,application/pdf,image/png,image/jpeg,image/tiff,image/bmp" hint="PDF, PNG, JPG, TIFF, or BMP" onChange={chooseFile} />
      <div className="form-grid"><label className="field"><span>Output format</span><select value={format} onChange={e => setFormat(e.target.value)}><option value="docx">Word (.docx)</option><option value="xlsx">Excel (.xlsx)</option><option value="pptx">PowerPoint (.pptx)</option><option value="searchable_pdf">PDF (.pdf)</option><option value="txt">TXT (.txt)</option></select></label><label className="field"><span>Mode</span><select value={mode} onChange={e => setMode(e.target.value)}><option value="visual">Preserve original appearance</option><option value="editable">Prioritize editing</option><option value="hybrid">Hybrid</option></select></label><label className={`field ${file&&!isPdf?"field-disabled":""}`}><span>Pages to process</span><input value={pages} onChange={e => setPages(e.target.value)} placeholder={file&&!isPdf?"Available for PDF files only":"Example: 1-5, 8"} disabled={!file||!isPdf} /></label><label className="field"><span>OCR language</span><select value={language} onChange={e => setLanguage(e.target.value)}><option value="auto">Automatic</option><option value="vi">Vietnamese</option><option value="en">English</option><option value="vi+en">Vietnamese + English</option></select></label></div>
      <div className="checks"><label><input type="checkbox" defaultChecked /> Preserve fonts</label><label><input type="checkbox" defaultChecked /> Detect tables</label><label><input type="checkbox" defaultChecked /> Preserve images</label><label><input type="checkbox" defaultChecked /> Compare layout</label></div>
      {error && <div className="notice error">{error}</div>}<TimedActionButton label="Start conversion" loadingLabel="Converting..." isRunning={timer.isRunning} elapsedTime={timer.formattedTime} disabled={!file || busy} onClick={start} icon={busy ? <LoaderCircle className="spin" /> : undefined} success={!!job} error={!!error} />{job && <button className="primary result-download" onClick={async () => { try { const result = await downloadDocument(job); saveBlob(result.blob, result.filename); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not download the document."); } }}><Download /> Save document</button>}
    </article><PdfPreview file={file} /></div></section>;
}
