import { useEffect,useMemo,useState } from "react";
import { Download,Headphones,Link2,Save,ShieldCheck,VolumeX } from "lucide-react";
import FileDrop from "../components/FileDrop"; import TimedActionButton from "../components/TimedActionButton"; import { useElapsedTimer } from "../hooks/useElapsedTimer"; import { downloadVideo,extractAudio,muteVideo,saveBlob } from "../services/api";
type Result={blob:Blob;name:string}|null;
export default function DownloadPage(){
 const[url,setUrl]=useState("");const[quality,setQuality]=useState("balanced");const[videoFile,setVideoFile]=useState<File|null>(null);const[downloadResult,setDownloadResult]=useState<Result>(null);const[audioResult,setAudioResult]=useState<Result>(null);const[mutedResult,setMutedResult]=useState<Result>(null);const[downloadBusy,setDownloadBusy]=useState(false);const[audioBusy,setAudioBusy]=useState(false);const[message,setMessage]=useState("");const downloadTimer=useElapsedTimer();const audioTimer=useElapsedTimer();const videoPreview=useMemo(()=>videoFile?URL.createObjectURL(videoFile):"",[videoFile]);useEffect(()=>()=>{if(videoPreview)URL.revokeObjectURL(videoPreview);},[videoPreview]);
 async function startDownload(){if(downloadBusy)return;downloadTimer.start();try{setDownloadBusy(true);setMessage("");setDownloadResult(null);const blob=await downloadVideo(url,quality,"none");setDownloadResult({blob,name:"loca-video.mp4"});}catch(e){setMessage(e instanceof Error?e.message:"Could not download the video.");}finally{setDownloadBusy(false);downloadTimer.stop();}}
 async function startAudio(){if(!videoFile||audioBusy)return;audioTimer.start();try{setAudioBusy(true);setMessage("");setAudioResult(null);setMutedResult(null);const[audio,muted]=await Promise.all([extractAudio(videoFile),muteVideo(videoFile)]);const base=videoFile.name.replace(/\.[^.]+$/,"");setAudioResult({blob:audio,name:`${base}-audio.mp3`});setMutedResult({blob:muted,name:`${base}-muted.mp4`});}catch(e){setMessage(e instanceof Error?e.message:"Could not separate the video and audio.");}finally{setAudioBusy(false);audioTimer.stop();}}
 return <section><div className="page-heading"><div><span className="eyebrow">VIDEO EDITOR</span><h2>Download Video and Extract Audio</h2><p>Two essential tools in one workspace.</p></div><span className="safe"><ShieldCheck/> Data is processed locally</span></div>{message&&<div className="notice error">{message}</div>}<div className="split equal"><article className="card tool-card"><div className="card-title"><span className="number">01</span><div><h3>Download video</h3><p>Download from a direct link or a supported website.</p></div></div><label className="field"><span>Video URL</span><div className="input-icon"><Link2/><input value={url} onChange={e=>{setUrl(e.target.value);setDownloadResult(null);downloadTimer.reset();}} placeholder="https://example.com/video"/></div></label><div className="choice-grid">{[["small","Data saver","720p"],["balanced","Balanced","1080p"],["best","Best","Original quality"]].map(item=><button key={item[0]} className={quality===item[0]?"choice active":"choice"} onClick={()=>setQuality(item[0])}><i/><strong>{item[1]}</strong><small>{item[2]}</small></button>)}</div><TimedActionButton label="Download video" loadingLabel="Downloading..." isRunning={downloadTimer.isRunning} elapsedTime={downloadTimer.formattedTime} disabled={!url.trim()||downloadBusy} onClick={startDownload} icon={<Download/>} success={!!downloadResult} error={!!message}/>{downloadResult&&<div className="result"><span><strong>Video is ready</strong><small>Choose where to save it.</small></span><button className="primary" onClick={()=>saveBlob(downloadResult.blob,downloadResult.name)}><Save/> Save video</button></div>}</article><article className="card tool-card"><div className="card-title"><span className="number">02</span><div><h3>Separate video and audio</h3><p>Create a muted video and an audio-only file.</p></div></div><FileDrop file={videoFile} accept="video/*" hint="MP4, MOV, MKV, WebM, or AVI" onChange={file=>{setVideoFile(file);setAudioResult(null);setMutedResult(null);audioTimer.reset();}}/>{videoPreview&&<video className="compact-video" src={videoPreview} controls/>}<TimedActionButton label="Separate video and audio" loadingLabel="Creating two outputs..." isRunning={audioTimer.isRunning} elapsedTime={audioTimer.formattedTime} disabled={!videoFile||audioBusy} onClick={startAudio} icon={<Headphones/>} success={!!audioResult&&!!mutedResult} error={!!message}/>{mutedResult&&<div className="result"><span><strong><VolumeX/> Muted video</strong><small>{mutedResult.name}</small></span><button className="primary" onClick={()=>saveBlob(mutedResult.blob,mutedResult.name)}><Save/> Save video</button></div>}{audioResult&&<div className="result"><span><strong><Headphones/> Audio only</strong><small>{audioResult.name}</small></span><button className="primary" onClick={()=>saveBlob(audioResult.blob,audioResult.name)}><Save/> Save audio</button></div>}</article></div></section>;
}
