import { useEffect, useMemo, useState } from "react";
import { FlipHorizontal2, RotateCcw, RotateCw, Save, Undo2 } from "lucide-react";
import FileDrop from "../components/FileDrop";
import TimedActionButton from "../components/TimedActionButton";
import { useElapsedTimer } from "../hooks/useElapsedTimer";
import { rotateVideo, saveBlob } from "../services/api";

export default function RotateVideoPage() {
  const [file,setFile]=useState<File|null>(null); const [rotation,setRotation]=useState(0); const [mirror,setMirror]=useState(false); const [busy,setBusy]=useState(false); const [result,setResult]=useState<Blob|null>(null); const [error,setError]=useState(""); const timer=useElapsedTimer();
  const preview=useMemo(()=>file?URL.createObjectURL(file):"",[file]); useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  const hasChanges=rotation!==0||mirror;
  const rotationLabel=rotation===0?"None":rotation===90?"90° Right":rotation===180?"180°":rotation===270?"90° Left":`${rotation}°`;
  function changed(){setResult(null);setError("");timer.reset();}
  function rotateLeft(){setRotation(current=>(current+270)%360);changed();}
  function rotateRight(){setRotation(current=>(current+90)%360);changed();}
  function toggleMirror(){setMirror(current=>!current);changed();}
  function reset(){setRotation(0);setMirror(false);changed();}
  async function start(){if(!file||busy||!hasChanges)return;timer.start();setBusy(true);setError("");setResult(null);try{setResult(await rotateVideo(file,rotation,mirror));}catch(reason){setError(reason instanceof Error?reason.message:"Could not transform the video.");}finally{setBusy(false);timer.stop();}}
  return <section><div className="page-heading"><div><span className="eyebrow">VIDEO TRANSFORM</span><h2>Rotate Video</h2><p>Use Rotate Left, Rotate Right, and Mirror independently or combine them.</p></div></div>{error&&<div className="notice error">{error}</div>}<div className="split equal compress-layout"><article className="card"><div className="card-title"><span className="number">01</span><div><h3>Select video</h3><p>Choose the source video and set its orientation.</p></div></div><FileDrop file={file} accept="video/*" hint="MP4, MOV, MKV, WebM, or AVI" onChange={value=>{setFile(value);setRotation(0);setMirror(false);setResult(null);setError("");timer.reset();}}/><h4 className="section-label">TRANSFORM</h4><div className="rotate-actions"><button type="button" disabled={!file} onClick={rotateLeft}><RotateCcw/><strong>Rotate Left</strong><small>90° counterclockwise</small></button><button type="button" disabled={!file} onClick={rotateRight}><RotateCw/><strong>Rotate Right</strong><small>90° clockwise</small></button><button type="button" disabled={!file} className={mirror?"active":""} onClick={toggleMirror}><FlipHorizontal2/><strong>Mirror</strong><small>{mirror?"Enabled":"Flip horizontally"}</small></button><button type="button" onClick={reset} disabled={!file||!hasChanges}><Undo2/><strong>Reset</strong><small>Original orientation</small></button></div></article><article className="right-stack"><div className="card preview-card"><div className="card-title compact"><span className="soft-icon"><RotateCw/></span><div><h3>Video preview</h3><p>Each control updates this preview immediately.</p></div></div><div className="video-frame rotate-preview">{preview?<video src={preview} controls style={{transform:`rotate(${rotation}deg) scaleX(${mirror?-1:1})`}}/>:<span>No video selected</span>}</div></div><div className="card output-card"><h3>Output settings</h3><div className="transform-summary"><span><strong>Rotation</strong><b>{rotationLabel}</b></span><span><strong>Mirror</strong><b>{mirror?"On":"Off"}</b></span></div><TimedActionButton label="Apply changes" loadingLabel="Processing video..." isRunning={timer.isRunning} elapsedTime={timer.formattedTime} disabled={!file||busy||!hasChanges} onClick={start} success={!!result} error={!!error}/>{result&&<button className="primary result-download" onClick={()=>saveBlob(result,`transformed-${file?.name.replace(/\.[^.]+$/,"")||"video"}.mp4`)}><Save/> Save video</button>}</div></article></div></section>;
}
