import { useMemo, useState } from "react";
import { LoaderCircle, RotateCcw, RotateCw, Save, Trash2 } from "lucide-react";
import FileDrop from "../components/FileDrop"; import PdfPreview from "../components/PdfPreview"; import TimedActionButton from "../components/TimedActionButton"; import { useElapsedTimer } from "../hooks/useElapsedTimer"; import { inspectPdf,rotatePdf,saveBlob,type DownloadResult,type PdfInfo } from "../services/api"; import { parsePageRanges } from "../services/pdfRanges";

export default function RotatePdfPage(){
  const[file,setFile]=useState<File|null>(null);const[previewFile,setPreviewFile]=useState<File|null>(null);const[info,setInfo]=useState<PdfInfo|null>(null);const[ranges,setRanges]=useState("");const[rotation,setRotation]=useState<-90|90|180>(90);const[outputName,setOutputName]=useState("document_rotated.pdf");const[result,setResult]=useState<DownloadResult|null>(null);const[busy,setBusy]=useState(false);const[inspecting,setInspecting]=useState(false);const[error,setError]=useState("");const timer=useElapsedTimer();const parsed=useMemo(()=>parsePageRanges(ranges,info?.pages||0),[ranges,info?.pages]);
  async function choose(next:File|null){setFile(next);setPreviewFile(next);setInfo(null);setResult(null);setError("");timer.reset();if(!next)return;if(next.type!=="application/pdf"&&!next.name.toLowerCase().endsWith(".pdf")){setFile(null);setPreviewFile(null);setError("Only PDF files are accepted.");return;}setOutputName(`${next.name.replace(/\.pdf$/i,"")}_rotated.pdf`);setInspecting(true);try{const value=await inspectPdf(next);setInfo(value);setRanges(`1-${value.pages}`);}catch(reason){setError(reason instanceof Error?reason.message:"Could not read the PDF.");}finally{setInspecting(false);}}
  async function submit(){if(!file||!info||parsed.error||busy)return;timer.start();setBusy(true);setError("");setResult(null);try{const value=await rotatePdf(file,rotation,ranges,outputName);setResult(value);setPreviewFile(new File([value.blob],value.filename,{type:"application/pdf"}));}catch(reason){setError(reason instanceof Error?reason.message:"Could not rotate the PDF.");}finally{setBusy(false);timer.stop();}}
  return <section><div className="page-heading"><div><span className="eyebrow">DOCUMENT EDITOR</span><h2>Rotate PDF</h2><p>Rotate all pages or selected page ranges in 90-degree steps.</p></div></div><div className="document-layout pdf-tool-layout"><article className="card document-controls pdf-tool-controls"><div className="card-title"><span className="number">01</span><div><h3>PDF file and rotation</h3><p>Choose a file, select pages, and set the rotation direction.</p></div></div><FileDrop file={file} accept=".pdf,application/pdf" hint="PDF files only" onChange={choose}/>{file&&<div className="file-summary"><div><strong>{file.name}</strong><span>{(file.size/1048576).toFixed(2)} MB · {info?`${info.pages} pages`:inspecting?"Reading...":"Page count unavailable"}</span></div><button type="button" onClick={()=>void choose(null)} aria-label="Remove file"><Trash2/></button></div>}<label className="field"><span>Pages to rotate</span><input value={ranges} onChange={e=>{setRanges(e.target.value);setResult(null);setPreviewFile(file);timer.reset();}} placeholder="Example: 1, 3-5" disabled={!file||inspecting}/></label>{file&&ranges&&parsed.error&&<div className="field-error">{parsed.error}</div>}<div className="pdf-rotation-options"><button className={rotation===-90?"active":""} onClick={()=>{setRotation(-90);setResult(null);setPreviewFile(file);}}><RotateCcw/><span><strong>Rotate Left</strong><small>90° counterclockwise</small></span></button><button className={rotation===90?"active":""} onClick={()=>{setRotation(90);setResult(null);setPreviewFile(file);}}><RotateCw/><span><strong>Rotate Right</strong><small>90° clockwise</small></span></button><button className={rotation===180?"active":""} onClick={()=>{setRotation(180);setResult(null);setPreviewFile(file);}}><RotateCw/><span><strong>Rotate 180°</strong><small>Turn pages upside down</small></span></button></div><label className="field"><span>Output filename</span><input value={outputName} onChange={e=>setOutputName(e.target.value)} placeholder="document_rotated.pdf"/></label>{error&&<div className="notice error">{error}</div>}<TimedActionButton label="Rotate PDF" loadingLabel="Rotating PDF..." isRunning={timer.isRunning} elapsedTime={timer.formattedTime} disabled={!file||!info||!!parsed.error||busy||inspecting} onClick={submit} icon={busy?<LoaderCircle className="spin"/>:<RotateCw/>} success={!!result} error={!!error}/>{result&&<button className="primary result-download" onClick={()=>saveBlob(result.blob,result.filename)}><Save/> Save PDF</button>}</article><PdfPreview file={previewFile} pageCount={info?.pages} selectedPages={parsed.selected} status={result?"Rotated preview":`${parsed.selected.size}/${info?.pages||0} pages selected`}/></div></section>;
}
