import { useEffect, useMemo, useState } from "react";
import { FlipHorizontal2, RotateCcw, RotateCw, Save, Undo2 } from "lucide-react";
import FileDrop from "../components/FileDrop";
import TimedActionButton from "../components/TimedActionButton";
import { useElapsedTimer } from "../hooks/useElapsedTimer";
import { rotateVideo, saveBlob } from "../services/api";

export default function RotateVideoPage() {
  const [file,setFile]=useState<File|null>(null); const [rotation,setRotation]=useState(0); const [mirror,setMirror]=useState(false); const [busy,setBusy]=useState(false); const [result,setResult]=useState<Blob|null>(null); const [error,setError]=useState(""); const timer=useElapsedTimer();
  const preview=useMemo(()=>file?URL.createObjectURL(file):"",[file]); useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  function update(nextRotation:number,nextMirror=mirror){setRotation((nextRotation+360)%360);setMirror(nextMirror);setResult(null);timer.reset();}
  async function start(){if(!file||busy)return;timer.start();setBusy(true);setError("");setResult(null);try{setResult(await rotateVideo(file,rotation,mirror));}catch(reason){setError(reason instanceof Error?reason.message:"Could not rotate the video.");}finally{setBusy(false);timer.stop();}}
  return <section><div className="page-heading"><div><span className="eyebrow">VIDEO TRANSFORM</span><h2>Rotate Video</h2><p>Rotate the video in 90-degree steps or mirror it horizontally.</p></div></div>{error&&<div className="notice error">{error}</div>}<div className="split equal compress-layout"><article className="card"><div className="card-title"><span className="number">01</span><div><h3>Select video</h3><p>Choose the source video and set its orientation.</p></div></div><FileDrop file={file} accept="video/*" hint="MP4, MOV, MKV, WebM, or AVI" onChange={value=>{setFile(value);setRotation(0);setMirror(false);setResult(null);setError("");timer.reset();}}/><h4 className="section-label">TRANSFORM</h4><div className="rotate-actions"><button onClick={()=>update(rotation-90)}><RotateCcw/><strong>Rotate Left</strong><small>90° counterclockwise</small></button><button onClick={()=>update(rotation+90)}><RotateCw/><strong>Rotate Right</strong><small>90° clockwise</small></button><button className={mirror?"active":""} onClick={()=>update(rotation,!mirror)}><FlipHorizontal2/><strong>Mirror</strong><small>Flip horizontally</small></button><button onClick={()=>update(0,false)} disabled={rotation===0&&!mirror}><Undo2/><strong>Reset</strong><small>Original orientation</small></button></div></article><article className="right-stack"><div className="card preview-card"><div className="card-title compact"><span className="soft-icon"><RotateCw/></span><div><h3>Video preview</h3><p>Review the selected orientation before processing.</p></div></div><div className="video-frame rotate-preview">{preview?<video src={preview} controls style={{transform:`rotate(${rotation}deg) scaleX(${mirror?-1:1})`}}/>:<span>No video selected</span>}</div></div><div className="card output-card"><h3>Output settings</h3><div className="transform-summary"><span><strong>Rotation</strong><b>{rotation}°</b></span><span><strong>Mirror</strong><b>{mirror?"On":"Off"}</b></span></div><TimedActionButton label="Rotate video" loadingLabel="Processing video..." isRunning={timer.isRunning} elapsedTime={timer.formattedTime} disabled={!file||busy||(rotation===0&&!mirror)} onClick={start} success={!!result} error={!!error}/>{result&&<button className="primary result-download" onClick={()=>saveBlob(result,`rotated-${file?.name.replace(/\.[^.]+$/,"")||"video"}.mp4`)}><Save/> Save video</button>}</div></article></div></section>;
}
