import { useEffect, useMemo, useRef, useState } from "react";
import { Film, Music2, Pause, Play, Plus, Save, Scissors, Trash2, Type, Upload, Volume2 } from "lucide-react";
import { renderVideoProject, saveBlob } from "../services/api";

type VideoClip = { id: string; file: File; source: string; start: number; end: number };
type TextClip = { id: string; text: string; start: number; end: number };
type AudioClip = { id: string; file: File; start: number; sourceStart: number; duration: number; volume: number };
type Selection = { type: "video" | "text" | "audio"; id: string } | null;
const id = () => crypto.randomUUID();
const time = (value: number) => { const s = Math.max(0, Math.floor(value || 0)); return [Math.floor(s / 3600), Math.floor(s / 60) % 60, s % 60].map(v => String(v).padStart(2, "0")).join(":"); };
const clipDuration = (clip: VideoClip) => Math.max(0, clip.end - clip.start);

async function mediaDuration(file: File) {
  const url = URL.createObjectURL(file);
  try { return await new Promise<number>((resolve, reject) => { const media = document.createElement(file.type.startsWith("audio/") ? "audio" : "video"); media.preload = "metadata"; media.onloadedmetadata = () => resolve(media.duration); media.onerror = () => reject(new Error(`Không đọc được ${file.name}`)); media.src = url; }); }
  finally { URL.revokeObjectURL(url); }
}

async function mixAudio(items: AudioClip[], projectDuration: number) {
  if (!items.length) return null;
  const context = new AudioContext();
  try {
    const decoded = await Promise.all(items.map(async item => ({ item, buffer: await context.decodeAudioData(await item.file.arrayBuffer()) })));
    const rate = 44100; const offline = new OfflineAudioContext(2, Math.max(1, Math.ceil(projectDuration * rate)), rate);
    decoded.forEach(({ item, buffer }) => { const source = offline.createBufferSource(); const gain = offline.createGain(); source.buffer = buffer; gain.gain.value = item.volume; source.connect(gain).connect(offline.destination); source.start(item.start, item.sourceStart, Math.min(item.duration, buffer.duration - item.sourceStart)); });
    const rendered = await offline.startRendering(); const length = rendered.length; const wav = new ArrayBuffer(44 + length * 4); const view = new DataView(wav); const write = (o: number, s: string) => [...s].forEach((c, i) => view.setUint8(o + i, c.charCodeAt(0))); write(0, "RIFF"); view.setUint32(4, 36 + length * 4, true); write(8, "WAVEfmt "); view.setUint32(16, 16, true); view.setUint16(20, 1, true); view.setUint16(22, 2, true); view.setUint32(24, rate, true); view.setUint32(28, rate * 4, true); view.setUint16(32, 4, true); view.setUint16(34, 16, true); write(36, "data"); view.setUint32(40, length * 4, true); let offset = 44; for (let i = 0; i < length; i++) for (let channel = 0; channel < 2; channel++) { const sample = Math.max(-1, Math.min(1, rendered.getChannelData(channel)[i] || 0)); view.setInt16(offset, sample < 0 ? sample * 32768 : sample * 32767, true); offset += 2; }
    return new File([wav], "loca-timeline-audio.wav", { type: "audio/wav" });
  } finally { await context.close(); }
}

export default function StudioPage() {
  const [videos, setVideos] = useState<VideoClip[]>([]); const [texts, setTexts] = useState<TextClip[]>([]); const [audios, setAudios] = useState<AudioClip[]>([]); const [selection, setSelection] = useState<Selection>(null); const [playhead, setPlayhead] = useState(0); const [playing, setPlaying] = useState(false); const [draft, setDraft] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [result, setResult] = useState<Blob | null>(null);
  const videoInput = useRef<HTMLInputElement>(null); const audioInput = useRef<HTMLInputElement>(null); const videoRef = useRef<HTMLVideoElement>(null); const lanes = useRef<HTMLDivElement>(null); const videosRef = useRef<VideoClip[]>([]);
  useEffect(() => { videosRef.current = videos; }, [videos]); useEffect(() => () => videosRef.current.forEach(item => URL.revokeObjectURL(item.source)), []);
  const offsets = useMemo(() => { let cursor = 0; return videos.map(item => { const value = cursor; cursor += clipDuration(item); return value; }); }, [videos]);
  const videoDuration = videos.reduce((sum, item) => sum + clipDuration(item), 0); const projectDuration = Math.max(1, videoDuration, ...texts.map(item => item.end), ...audios.map(item => item.start + item.duration));
  const foundActiveIndex = offsets.findIndex((offset, index) => playhead >= offset && playhead <= offset + clipDuration(videos[index])); const activeIndex = foundActiveIndex >= 0 ? foundActiveIndex : -1; const active = activeIndex >= 0 ? videos[activeIndex] : undefined;
  useEffect(() => { if (!active || !videoRef.current) return; const local = active.start + Math.max(0, playhead - (offsets[activeIndex] || 0)); if (Math.abs(videoRef.current.currentTime - local) > .12) videoRef.current.currentTime = local; }, [active?.id, playhead]);

  async function importVideos(files: FileList | null) { if (!files?.length) return; try { const additions = await Promise.all(Array.from(files).map(async file => ({ id: id(), file, source: URL.createObjectURL(file), start: 0, end: await mediaDuration(file) }))); setVideos(old => [...old, ...additions]); setSelection({ type: "video", id: additions[0].id }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không đọc được video."); } }
  async function importAudios(files: FileList | null) { if (!files?.length) return; try { const additions = await Promise.all(Array.from(files).map(async file => ({ id: id(), file, start: playhead, sourceStart: 0, duration: await mediaDuration(file), volume: 1 }))); setAudios(old => [...old, ...additions]); setSelection({ type: "audio", id: additions[0].id }); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không đọc được âm thanh."); } }
  function seek(value: number) { videoRef.current?.pause(); setPlaying(false); setPlayhead(Math.max(0, Math.min(value, projectDuration))); }
  async function toggle() { if (!active || !videoRef.current) return; if (videoRef.current.paused) await videoRef.current.play(); else videoRef.current.pause(); }
  function splitSelected() {
    if (!selection) return;
    if (selection.type === "video") { const index = videos.findIndex(item => item.id === selection.id); if (index < 0) return; const item = videos[index]; const local = playhead - offsets[index]; if (local <= .05 || local >= clipDuration(item) - .05) return; const cut = item.start + local; const left = { ...item, id: id(), source: URL.createObjectURL(item.file), end: cut }; const right = { ...item, id: id(), source: URL.createObjectURL(item.file), start: cut }; URL.revokeObjectURL(item.source); setVideos(old => [...old.slice(0, index), left, right, ...old.slice(index + 1)]); setSelection({ type: "video", id: right.id }); }
    if (selection.type === "text") { const item = texts.find(value => value.id === selection.id); if (!item || playhead <= item.start || playhead >= item.end) return; const left = { ...item, id: id(), end: playhead }; const right = { ...item, id: id(), start: playhead }; setTexts(old => old.flatMap(value => value.id === item.id ? [left, right] : [value])); setSelection({ type: "text", id: right.id }); }
    if (selection.type === "audio") { const item = audios.find(value => value.id === selection.id); const local = item ? playhead - item.start : 0; if (!item || local <= 0 || local >= item.duration) return; const left = { ...item, id: id(), duration: local }; const right = { ...item, id: id(), start: playhead, sourceStart: item.sourceStart + local, duration: item.duration - local }; setAudios(old => old.flatMap(value => value.id === item.id ? [left, right] : [value])); setSelection({ type: "audio", id: right.id }); }
    setResult(null);
  }
  function removeSelected() { if (!selection) return; if (selection.type === "video") setVideos(old => old.filter(item => { if (item.id === selection.id) URL.revokeObjectURL(item.source); return item.id !== selection.id; })); if (selection.type === "text") setTexts(old => old.filter(item => item.id !== selection.id)); if (selection.type === "audio") setAudios(old => old.filter(item => item.id !== selection.id)); setSelection(null); setResult(null); }
  function addText() { if (!draft.trim()) return; const item = { id: id(), text: draft.trim(), start: playhead, end: playhead + 5 }; setTexts(old => [...old, item]); setSelection({ type: "text", id: item.id }); setDraft(""); }
  function dropAt(event: React.DragEvent, type: "text" | "audio", itemId: string) { event.preventDefault(); if (!lanes.current) return; const rect = lanes.current.getBoundingClientRect(); const start = Math.max(0, Math.min(projectDuration, (event.clientX - rect.left) / rect.width * projectDuration)); if (type === "text") setTexts(old => old.map(item => item.id === itemId ? { ...item, start, end: start + (item.end - item.start) } : item)); else setAudios(old => old.map(item => item.id === itemId ? { ...item, start } : item)); }
  function reorderVideo(fromId: string, toId: string) { const from = videos.findIndex(v => v.id === fromId), to = videos.findIndex(v => v.id === toId); if (from < 0 || to < 0 || from === to) return; const next = [...videos]; const [moved] = next.splice(from, 1); next.splice(to, 0, moved); setVideos(next); }
  async function exportProject() { if (!videos.length || busy) return; try { setBusy(true); setError(""); const mixed = await mixAudio(audios, projectDuration); const blob = await renderVideoProject(videos.map(v => v.file), videos.map(v => ({ start: v.start, end: v.end })), texts.map(({ text, start, end }) => ({ text, start, end })), mixed); setResult(blob); } catch (reason) { setError(reason instanceof Error ? reason.message : "Không thể xuất video."); } finally { setBusy(false); } }
  const canCut = !!selection && (selection.type === "video" ? (() => { const index = videos.findIndex(item => item.id === selection.id); if (index < 0) return false; const local = playhead - offsets[index]; return local > .05 && local < clipDuration(videos[index]) - .05; })() : selection.type === "text" ? texts.some(item => item.id === selection.id && playhead > item.start && playhead < item.end) : audios.some(item => item.id === selection.id && playhead > item.start && playhead < item.start + item.duration));
  const pos = (start: number) => `${start / projectDuration * 100}%`; const width = (duration: number) => `${Math.max(.8, duration / projectDuration * 100)}%`;
  return <section className="studio capcut-studio"><input ref={videoInput} className="studio-file-input" type="file" multiple accept="video/*" onChange={e => { void importVideos(e.target.files); e.target.value = ""; }} /><input ref={audioInput} className="studio-file-input" type="file" multiple accept="audio/*" onChange={e => { void importAudios(e.target.files); e.target.value = ""; }} />
    <div className="studio-bar"><div><strong>Dự án Loca Editor</strong><span>{videos.length} video · {time(projectDuration)}</span></div><div className="studio-actions">{result && <button onClick={() => saveBlob(result, "loca-project.mp4")}><Save /> Lưu video</button>}<button className="studio-export" disabled={!videos.length || busy} onClick={() => void exportProject()}>{busy ? "Đang xuất..." : "Xuất video"}</button></div></div>{error && <div className="studio-error">{error}</div>}
    <div className="capcut-preview"><div className="screen">{active ? <video key={active.id} ref={videoRef} src={active.source} onLoadedMetadata={() => seek(playhead)} onTimeUpdate={e => { const next = (offsets[activeIndex] || 0) + Math.max(0, e.currentTarget.currentTime - active.start); setPlayhead(next); if (e.currentTarget.currentTime >= active.end) { e.currentTarget.pause(); if (activeIndex < videos.length - 1) { setPlayhead(offsets[activeIndex + 1]); setTimeout(() => void videoRef.current?.play(), 0); } } }} onPlay={() => setPlaying(true)} onPause={() => setPlaying(false)} /> : <div><Play /><p>Nhập video để bắt đầu</p></div>}{texts.filter(t => playhead >= t.start && playhead <= t.end).map(t => <div className="video-text-overlay" key={t.id}>{t.text}</div>)}</div><div className="player"><span>{time(playhead)}</span><button disabled={!active} onClick={() => void toggle()}>{playing ? <Pause /> : <Play />}</button><Volume2 /><input className="seek" type="range" min="0" max={projectDuration} step=".05" value={playhead} onInput={e => seek(Number(e.currentTarget.value))} /><span>{time(projectDuration)}</span></div></div>
    <div className="capcut-toolbar"><button disabled={!canCut} onClick={splitSelected}><Scissors /> Cắt tại playhead</button><label>Thời gian<input type="number" min="0" max={projectDuration} step=".1" value={playhead.toFixed(1)} onChange={e => seek(Number(e.target.value))} /></label><button disabled={!selection} onClick={removeSelected}><Trash2 /> Xóa</button><span>Chọn một đối tượng rồi kéo playhead đến vị trí cần cắt.</span></div>
    <div className="capcut-timeline" ref={lanes}><div className="timeline-ruler"><span>00:00</span><span>{time(projectDuration / 2)}</span><span>{time(projectDuration)}</span></div><div className="project-playhead" style={{ left: pos(playhead) }} />
      <div className="capcut-lane"><strong>Video</strong><div>{videos.map((v, i) => <button key={v.id} draggable onDragStart={e => e.dataTransfer.setData("video-id", v.id)} onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); reorderVideo(e.dataTransfer.getData("video-id"), v.id); }} className={`timeline-block video-block ${selection?.type === "video" && selection.id === v.id ? "selected" : ""}`} style={{ left: pos(offsets[i]), width: width(clipDuration(v)) }} onClick={() => setSelection({ type: "video", id: v.id })}><Film />{v.file.name}</button>)}</div></div>
      <div className="capcut-lane"><strong>Văn bản</strong><div onDragOver={e => e.preventDefault()}>{texts.map(t => <button key={t.id} draggable onDragEnd={e => dropAt(e, "text", t.id)} className={`timeline-block text-block ${selection?.type === "text" && selection.id === t.id ? "selected" : ""}`} style={{ left: pos(t.start), width: width(t.end - t.start) }} onClick={() => setSelection({ type: "text", id: t.id })}><Type />{t.text}</button>)}<div className="lane-add"><input value={draft} onChange={e => setDraft(e.target.value)} placeholder="Nhập chữ" /><button onClick={addText}><Plus /></button></div></div></div>
      <div className="capcut-lane"><strong>Âm thanh</strong><div onDragOver={e => e.preventDefault()}>{audios.map(a => <button key={a.id} draggable onDragEnd={e => dropAt(e, "audio", a.id)} className={`timeline-block audio-block ${selection?.type === "audio" && selection.id === a.id ? "selected" : ""}`} style={{ left: pos(a.start), width: width(a.duration) }} onClick={() => setSelection({ type: "audio", id: a.id })}><Music2 />{a.file.name}</button>)}<button className="lane-import" onClick={() => audioInput.current?.click()}><Plus /> Âm thanh</button></div></div>
    </div><button className="floating-import" onClick={() => videoInput.current?.click()}><Upload /> Nhập video</button>
  </section>;
}
