create table if not exists public.user_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'user' check (role in ('admin', 'agent', 'user')),
  status text not null default 'active' check (status in ('active', 'locked', 'expired')),
  expires_at timestamptz null,
  force_password_change boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  created_by uuid null references auth.users(id) on delete set null,
  updated_by uuid null references auth.users(id) on delete set null
);
create index if not exists user_access_role_idx on public.user_access(role);
create index if not exists user_access_status_idx on public.user_access(status);
alter table public.user_access enable row level security;
revoke all on public.user_access from anon, authenticated;

create or replace function public.set_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end
$$;
drop trigger if exists user_access_set_updated_at on public.user_access;
create trigger user_access_set_updated_at before update on public.user_access for each row execute function public.set_updated_at();

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_user_id uuid null references auth.users(id) on delete set null,
  target_user_id uuid null,
  action text not null,
  before jsonb null,
  after jsonb null,
  request_id text null,
  created_at timestamptz not null default now()
);
create index if not exists admin_audit_target_idx on public.admin_audit_log(target_user_id, created_at desc);
alter table public.admin_audit_log enable row level security;
revoke all on public.admin_audit_log from anon, authenticated;

update auth.users set raw_app_meta_data = coalesce(raw_app_meta_data, '{}'::jsonb) || '{"role":"admin"}'::jsonb where email = 'loctuyen001@gmail.com';
insert into public.user_access (user_id, role, status, expires_at, force_password_change)
select id, 'admin', 'active', null, false from auth.users where email = 'loctuyen001@gmail.com'
on conflict (user_id) do update set role='admin', status='active', expires_at=null, force_password_change=false;
